apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-beta-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/alex/volumes/mysql-beta-pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-beta-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
