version: '2'

# same as 
# docker rn -p 80:4000 -v $(pwd):/site bretfisher/jekyll-serve

services:
  jekyll:
    image: bretfisher/jekyll-serve
    volume: 
      - .:/site
    ports:
      - '80:4000'