version: '3.1'

services:
  mysql-beta:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=beta
      - MYSQL_ROOT_PASSWORD=alex123
      - MYSQL_USER=alex
      - MYSQL_PASSWORD=alex123
    ports:
      - '3306:3306'
    volumes:
      - ~/dockeration/volumes/mysql-beta:/var/lib/mysql 

# docker container run -d \
#                      --name mysql-beta \
#                      -e MYSQL_ROOT_PASSWORD=alex123 \
#                      -e MYSQL_DATABASE=beta \
#                      -e MYSQL_USER=alex \
#                      -e MYSQL_PASSWORD=alex123 \
#                      -p 3306:3306 \
#                      -v ~/dockeration/volumes/mysql-beta:/var/lib/mysql 
#                      mysql:8